[package]
name = "coubot"
version = "0.1.0"
authors = ["Alex Hincu <teeseal@sorta.moe>"]
edition = "2018"

[dependencies]
serenity = "0.6"
regex = "1.2.1"
lazy_static = "1.4.0"
url = "2.1.0"
reqwest = "0.9"
serde_json = "1.0"
tempfile = "3.1.0"
